name: status

on: [push]

jobs:

  lint-test:

    runs-on: ubuntu-latest

    container:
      image: analysiscenter1/ds-py3:latest

    steps:
    - name: Checkout SeismicPro
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update pylint
      run: pip3 install -U pylint

    - name: Check pylint
      run: pylint -rn --persistent=n --rcfile pylintrc seismicpro

    - name: Run tests
      if: always()
      run: pytest -m "not slow" --disable-pytest-warnings -v seismicpro/src/tests
